---
- hosts: localhost
  remote_user: root

  tasks:
  - name: install iscsi packages for ubuntu/deb
    apt:
      update_cache=yes
      state=latest
      name={{item}}
    with_items:
    - multipath-tools
    - open-iscsi
    when: (ansible_facts['distribution'] == "Ubuntu" ) or
          (ansible_facts['distribution'] == "Debian" )

  - name: install iscsi packages for rhel/centos/fedora
    yum:
      update_cache=yes
      state=latest
      name={{item}}
    with_items:
    - iscsi-initiator-utils
    - device-mapper-multipath
    when: (ansible_facts['distribution'] == "CentOS" ) or
          (ansible_facts['distribution'] == "RHEL" )
